name: Build and Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends libdbus-1-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: bing_wallpaper_downloader
          path: target/release/bing_wallpaper_downloader

  clippy_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends libdbus-1-dev

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
